/**
 * Created by vepe on 08/03/17.
 */
module.exports = {
  noChange: ['Nothing new',
    'It\'s pretty quiet around here',
    'Not much to see today :thinking_face:',
    'Come back tomorrow.'],
  smallestPositiveChange: ['At least you\'re not losing money!',
    'I guess that\'s something...',
    'Welp',
  'Investing is weird man',
  '$ave that money!'],
  smallPositiveChange: ['Not bad, not bad...',
    'You\'re doing ok'],
  postiveChange: ['Today was a p good day!',
    ':money_mouth_face:'],
  bigPostiveChange: ['Now you\'re making money! :ok_hand:',
  ':moneybag:',
  'Cash rules everything around me! :moneybag:'],
  biggestPositiveChange: ['The sky is the limit!',
  'Dolla dolla bills y\'all!',
  'Shake that money maker!'],
  smallestNegativeChange: ['Could have been worse.',
    'As far as losses go, this is p ok'],
  smallNegativeChange: ['Man, I dunno'],
  negativeChange: [':money_with_wings:'],
  bigNegativeChange: ['Shiiiiiiiit',
    'I dunno what to say man',
    'I should probably say something comforting',
    'At least you have your health',
    'I am holding you tight during this time of loss',
    'I will always be here for you'],
  biggestNegativeChange: ['Just know that my arms are wrapped around you during this time of loss.',
    'If Britney made it through 2008, you can make it through this.',
    'We never lose the ~people~ money we love. They live with us in our hearts for the rest of our lives.'],
};
